#!/bin/bash

STEPS=10
WIDTH=10000
HEIGHT=10000

cd ..
make run EXE=simple ARG_PRINT=0 ARG_STEPS=$STEPS ARG_WIDTH=$WIDTH ARG_HEIGHT=$HEIGHT >> test_local.log
make run EXE=simple_opt ARG_PRINT=0 ARG_STEPS=$STEPS ARG_WIDTH=$WIDTH ARG_HEIGHT=$HEIGHT >> test_local.log
make run EXE=threads ARG_PRINT=0 ARG_STEPS=$STEPS ARG_WIDTH=$WIDTH ARG_HEIGHT=$HEIGHT ARG_THREADS=8 >> test_local.log
make run EXE=nodes ARG_PRINT=0 ARG_STEPS=$STEPS ARG_WIDTH=$WIDTH ARG_HEIGHT=$HEIGHT ARG_NODES=2 >> test_local.log
make run EXE=hybrid ARG_PRINT=0 ARG_STEPS=$STEPS ARG_WIDTH=$WIDTH ARG_HEIGHT=$HEIGHT ARG_THREADS=4 ARG_NODES=2 >> test_local.log