#!/bin/bash

STEPS=10
WIDTH=20000
HEIGHT=20000

cd ..
make run EXE=simple ARG_PRINT=0 ARG_STEPS=$STEPS ARG_WIDTH=$WIDTH ARG_HEIGHT=$HEIGHT > test/out/test_simple_$WIDTH.log
make run EXE=simple_opt ARG_PRINT=0 ARG_STEPS=$STEPS ARG_WIDTH=$WIDTH ARG_HEIGHT=$HEIGHT > test/out/test_simple_opt_$WIDTH.log
make run EXE=threads ARG_PRINT=0 ARG_STEPS=$STEPS ARG_WIDTH=$WIDTH ARG_HEIGHT=$HEIGHT ARG_THREADS=8 > test/out/test_threads_$WIDTH.log
make run EXE=nodes ARG_PRINT=0 ARG_STEPS=$STEPS ARG_WIDTH=$WIDTH ARG_HEIGHT=$HEIGHT ARG_NODES=2 > test/out/test_nodes_$WIDTH.log
make run EXE=hybrid ARG_PRINT=0 ARG_STEPS=$STEPS ARG_WIDTH=$WIDTH ARG_HEIGHT=$HEIGHT ARG_THREADS=4 ARG_NODES=2 > test/out/test_hybrid_$WIDTH.log